# use C-s, since it's hame row
set-option -g prefix C-s
unbind-key C-s
bind-key C-s send-prefix
set -g base-index 1

# Easy config reload
bind-key R source-file ~/.tmux.conf \; display-message "Reloaded!"

# VIM <3
setw -g mode-keys vi

# Mouse
setw -g mouse on

set-option -g default-terminal screen-256color

bind-key : command-prompt
bind-key r refresh-client
bind-key L clear-history

bind-key space next-window
bind-key bspace previous-window
bind-key enter next-layout

# Use vim-like keys for splits and windows
bind-key v split-window -h
bind-key s split-window -v

bind-key x kill-pane

bind-key t select-pane -L
bind-key h select-pane -D
bind-key a select-pane -U
bind-key r select-pane -R

bind-key T resize-pane -L 5
bind-key H resize-pane -D 5
bind-key A resize-pane -U 5
bind-key R resize-pane -R 5

# Plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @catppuccin_flavour 'frappe'
set -g status-position bottom

run '~/.tmux/plugins/tpm/tpm'
